site_name: mxlpy docs
site_url: https://computational-biology-aachen.github.io/mxl-models/
site_dir: dist
repo_url: https://github.com/Computational-Biology-Aachen/mxl-models/
use_directory_urls: false

nav:
  - Home: index.md
  - dynamic_enterobactin: _dynamic_enterobactin.ipynb
  - population_dynamics: _population_dynamics.ipynb
  - tripartite_dynamics: _tripartite_dynamics.ipynb
  - davis2017: davis2017.ipynb
  - ebeling2026: ebeling2026.ipynb
  - ebenhoeh2014: ebenhoeh2014.ipynb
  - elowitz2000_repressilator: elowitz2000_repressilator.ipynb
  - lotka_volterra: lotka_volterra.ipynb
  - matuszynska2016_npq: matuszynska2016_npq.ipynb
  - matuszynska2016_phd: matuszynska2016_phd.ipynb
  - matuszynska2019: matuszynska2019.ipynb
  - nguyen2026_tomato: nguyen2026_tomato.ipynb
  - pfennig2024_synechocystis: pfennig2024_synechocystis.ipynb
  - poolman2000: poolman2000.ipynb
  - prigogine1968_brusselator: prigogine1968_brusselator.ipynb
  - saadat2021: saadat2021.ipynb
  - selkov1968_oscillator: selkov1968_oscillator.ipynb
  - yokota1985: yokota1985.ipynb

theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.instant.prefetch
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal

extra:
  version:
    provider: mike
    default: stable

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed
  - toc:
      permalink: true

plugins:
  - search
  - mkdocs-jupyter:
      ignore_h1_titles: True
      execute: true
      ignore: ["assets/*.ipynb"]
      include_requirejs: true
      custom_mathjax_url:
        "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/lates\
        t.js?config=TeX-AMS_CHTML-full,Safe"

extra_css:
  - stylesheets/extra.css
